/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: dudecon (https://sketchfab.com/dudecon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bastard-sword-4c43ea7ce78e4fe89a5f136366b91f51
Title: Bastard Sword
*/
"use client";
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function BastardSword(props) {
  const { nodes, materials } = useGLTF('/models/bastard_sword.glb')
   const modelRef = useRef();
    const size = 2.5;
    const position = {
      x: 0,
      y: 0.7,
      z: 0,
    }
    
    const rotation = {
        x: 0.2,
        y: 0,
        z: Math.PI/2,
    }

     useFrame((state) => {
                // modelRef.current.position.y =
                //   position.y + Math.sin(state.clock.elapsedTime * 1.1) * 0.15;
                //   //modelRef.current.rotation.y = rotationY;
                  modelRef.current.rotation.y += 0.02;
                //modelRef.current.rotation.x += 0.01;
               //modelRef.current.rotation.z += 0.01;
                 // modelRef.current.rotation.y += hovered ? 0.02 : 0.001;
              });
          
  return (
    <group {...props} dispose={null}
    ref={modelRef}
    position={[position.x, position.y, position.z]}
    scale={[size, size, size]}
    rotation={[rotation.x, rotation.y, rotation.z]} >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials['Material.001']}
        rotation={[0,  0, 0]}
        scale={0.145}
      />
    </group>
  )
}

useGLTF.preload('/models/bastard_sword.glb')

