/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Justin Rajan (https://sketchfab.com/justin.rajan.6619)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vegeta-7991783180824cb198335e8b3acc9e1c
Title: Vegeta
*/
"use client";
import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Vegeta(props) {
    const modelRef = useRef()
    const { nodes, materials, animations } = useGLTF('/models/vegeta.glb')
    const { actions } = useAnimations(animations, modelRef)
    console.log(nodes, materials, animations);
    const size = 1;
    const position = {
        x: 0,
        y: -1.5,
        z: 0,
    }

    // useEffect(() => {
    //     if (actions["mixamo.com"]) { // Remplace "Idle" par le nom de ton animation
    //         actions["mixamo.com"].timeScale = 0.9;
    //         actions["mixamo.com"].play();
    //     }
    // }, [actions]);
    console.log(Object.keys(actions));

    useFrame((state) => {
        modelRef.current.position.y =
            position.y + Math.sin(state.clock.elapsedTime * 1.1) * 0.15;
        //modelRef.current.rotation.y = rotationY;
        modelRef.current.rotation.y += 0.01;
        // modelRef.current.rotation.y += hovered ? 0.02 : 0.001;
    });
    return (
        <group ref={modelRef} {...props} dispose={null}
            position={[position.x, position.y, position.z]}
            scale={[size, size, size]}
            rotation={[0.2, -1.5, 0]}
        >
            <group name="Sketchfab_Scene">
                <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
                    <group
                        name="d9e868a2cc8f4a519301fb1722dee70bfbx"
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.01}>
                        <group name="Object_2">
                            <group name="RootNode">
                                <group name="Object_4">
                                    <primitive object={nodes._rootJoint} />
                                    <skinnedMesh
                                        name="Object_7"
                                        geometry={nodes.Object_7.geometry}
                                        material={materials.Material_80}
                                        skeleton={nodes.Object_7.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_9"
                                        geometry={nodes.Object_9.geometry}
                                        material={materials.Material_82}
                                        skeleton={nodes.Object_9.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_11"
                                        geometry={nodes.Object_11.geometry}
                                        material={materials.Material_84}
                                        skeleton={nodes.Object_11.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_13"
                                        geometry={nodes.Object_13.geometry}
                                        material={materials.Material_86}
                                        skeleton={nodes.Object_13.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_15"
                                        geometry={nodes.Object_15.geometry}
                                        material={materials.Material_88}
                                        skeleton={nodes.Object_15.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_17"
                                        geometry={nodes.Object_17.geometry}
                                        material={materials.Material_90}
                                        skeleton={nodes.Object_17.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_19"
                                        geometry={nodes.Object_19.geometry}
                                        material={materials.Material_45}
                                        skeleton={nodes.Object_19.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_21"
                                        geometry={nodes.Object_21.geometry}
                                        material={materials.Material_46}
                                        skeleton={nodes.Object_21.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_23"
                                        geometry={nodes.Object_23.geometry}
                                        material={materials.Material_78}
                                        skeleton={nodes.Object_23.skeleton}
                                    />
                                    <group name="Object_6" position={[0, -0.253, 0.261]} scale={0.015} />
                                    <group name="Object_8" position={[0, -0.253, 0.261]} scale={0.015} />
                                    <group name="Object_10" position={[0, -0.253, 0.261]} scale={0.015} />
                                    <group name="Object_12" position={[0, -0.253, 0.261]} scale={0.015} />
                                    <group name="Object_14" position={[0, -0.253, 0.261]} scale={0.015} />
                                    <group name="Object_16" position={[0, -0.253, 0.261]} scale={0.015} />
                                    <group name="Object_18" position={[0, -0.253, 0.261]} scale={0.015} />
                                    <group name="Object_20" position={[0, -0.253, 0.261]} scale={0.015} />
                                    <group name="Object_22" position={[0, -0.253, 0.261]} scale={0.015} />
                                    <group name="root">
                                        <group name="node_id14" scale={0.001}>
                                            <group name="node_id141" />
                                            <group name="node_id142" />
                                            <group name="node_id143" />
                                            <group name="node_id144" />
                                            <group name="node_id145" />
                                            <group name="node_id146" />
                                            <group name="node_id147" />
                                            <group name="node_id148" />
                                        </group>
                                    </group>
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/models/vegeta.glb')

